export const PORTAL_HOME_PATH = "/";

export const applicationPaths: Record<string, string> = {
  "compras-protheus": "/compras/protheus",
  "importacoes-compras-protheus": "/importacoes/compras-protheus",
  "importacoes-empresas": "/importacoes/empresas",
  "importacoes-filiais": "/importacoes/filiais",
  "importacoes-armazens": "/importacoes/armazens",
  "importacoes-locais-estoque": "/importacoes/locais-estoque",
  "importacoes-unidades": "/importacoes/unidades",
  "importacoes-centros-custo": "/importacoes/centros-custo",
  "importacoes-tipos-produto": "/importacoes/tipos-produto",
  "importacoes-usuarios": "/importacoes/usuarios",
  "importacoes-funcionarios": "/importacoes/funcionarios",
  "importacoes-fornecedores": "/importacoes/fornecedores",
  "importacoes-produtos": "/importacoes/produtos",
  administracao: "/usuarios",
  "usuarios-solicitacoes": "/usuarios",
  "perfis-acesso": "/perfis-acesso",
  cadastros: "/cadastros/funcionarios",
  "cadastros-empresas": "/cadastros/empresas",
  "cadastros-filiais": "/cadastros/filiais",
  "cadastros-armazens": "/cadastros/armazens",
  "cadastros-locais-estoque": "/cadastros/locais-estoque",
  "cadastros-unidades": "/cadastros/unidades",
  "cadastros-centros-custo": "/cadastros/centros-custo",
  "cadastros-tipos-produto": "/cadastros/tipos-produto",
  "cadastros-usuarios": "/cadastros/usuarios",
  funcionarios: "/cadastros/funcionarios",
  fornecedores: "/cadastros/fornecedores",
  produtos: "/cadastros/produtos",
  "chaves-nf": "/recebimentos/nf",
  almoxarifado: "/almoxarifado/requisicoes",
  "almoxarifado-requisicoes": "/almoxarifado/requisicoes",
  "almoxarifado-atendimentos": "/almoxarifado/atendimentos",
  "almoxarifado-devolucoes": "/almoxarifado/devolucoes",
  "almoxarifado-movimentacoes": "/almoxarifado/movimentacoes",
  "almoxarifado-estoque": "/almoxarifado/estoque",
  "almoxarifado-ferramentas": "/almoxarifado/ferramentas",
};
