import { useState } from "react";
import { AlertTriangle, CheckCircle2, Loader2, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

const nf = (value: number) => Number(value ?? 0).toLocaleString("pt-BR");
export default function AuditBacklog() {
  const [status, setStatus] = useState<"aberto" | "em_tratativa" | "resolvido" | "ignorado" | undefined>();
  const kpis = trpc.auditBacklog.kpis.useQuery();
  const findings = trpc.auditBacklog.findings.useQuery({ status, limit: 100, offset: 0 });
  const sync = trpc.auditBacklog.sync.useMutation({ onSuccess: result => { toast.success(`${result.findingCount.toLocaleString("pt-BR")} findings sincronizados.`); findings.refetch(); kpis.refetch(); }, onError: error => toast.error(error.message) });
  return <main className="page-wrap max-w-7xl"><header className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Administração · Auditoria</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-0.055em] text-slate-950">Backlog da auditoria</h1><p className="mt-3 max-w-3xl text-sm font-medium leading-6 text-slate-500">Pendências derivadas da auditoria, separadas dos dados brutos.</p></div><Button onClick={() => sync.mutate()} disabled={sync.isPending}>{sync.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <RefreshCw className="mr-2 h-4 w-4" />}Sincronizar auditoria</Button></header>
    <div className="mb-5 grid gap-4 sm:grid-cols-4"><div className="sc-surface p-5"><p className="text-xs font-bold uppercase text-slate-500">Abertas</p><p className="mt-2 text-2xl font-extrabold">{nf(kpis.data?.open_count)}</p></div><div className="sc-surface p-5"><p className="text-xs font-bold uppercase text-slate-500">Vencidas</p><p className="mt-2 text-2xl font-extrabold text-rose-700">{nf(kpis.data?.overdue_count)}</p></div><div className="sc-surface p-5"><p className="text-xs font-bold uppercase text-slate-500">Resolvidas em 30 dias</p><p className="mt-2 text-2xl font-extrabold text-emerald-700">{nf(kpis.data?.resolved_30d)}</p></div><div className="sc-surface p-5"><p className="text-xs font-bold uppercase text-slate-500">Total</p><p className="mt-2 text-2xl font-extrabold">{nf(kpis.data?.total_count)}</p></div></div>
    <div className="mb-4 flex flex-wrap gap-2"><select className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm font-bold" value={status ?? ""} onChange={event => setStatus((event.target.value || undefined) as typeof status)}><option value="">Todos os status</option><option value="aberto">Aberto</option><option value="em_tratativa">Em tratativa</option><option value="resolvido">Resolvido</option><option value="ignorado">Ignorado</option></select></div>
    <section className="sc-surface overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-extrabold">Pendências</h2><p className="mt-1 text-xs text-slate-500">A sincronização preserva o histórico e não altera as fontes brutas.</p></div>{findings.isLoading ? <div className="p-6"><Loader2 className="h-5 w-5 animate-spin" /></div> : <div className="max-h-[620px] overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs font-extrabold uppercase text-slate-500"><tr><th className="p-3">Fonte</th><th className="p-3">Categoria</th><th className="p-3">Tipo</th><th className="p-3">Chave</th><th className="p-3">Status</th><th className="p-3">Detalhe</th></tr></thead><tbody>{(findings.data ?? []).map(item => <tr key={item.id} className="border-t border-slate-100 align-top"><td className="p-3 font-bold">{item.source}</td><td className="p-3">{item.category === "EXCECAO" ? <AlertTriangle className="h-4 w-4 text-amber-600" /> : <CheckCircle2 className="h-4 w-4 text-slate-500" />}</td><td className="p-3 whitespace-nowrap">{item.kind}</td><td className="p-3 font-mono text-xs">{item.sourceKey}</td><td className="p-3 whitespace-nowrap">{item.status}</td><td className="p-3">{item.detail}</td></tr>)}</tbody></table></div>}</section>
  </main>;
}
