import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatDate, formatMoney, formatNumber } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { Boxes, ChartNoAxesCombined, CircleDollarSign, FileUp, RotateCw, Store, Tags } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

const metrics = [
  { key: "salesValue13M", label: "Vendas acumuladas", icon: CircleDollarSign, tone: "blue", format: formatMoney },
  { key: "stockValue", label: "Estoque financeiro", icon: Boxes, tone: "pink", format: formatMoney },
  { key: "turnover", label: "Giro", icon: RotateCw, tone: "blue", format: (value: number) => formatNumber(value, 2) },
  { key: "excessValue", label: "Excedente", icon: ChartNoAxesCombined, tone: "blue", format: formatMoney },
] as const;

type FilterState = { branch: string; curve: string; productType: string; family: string; subfamily: string };

export default function Dashboard() {
  const [, setLocation] = useLocation();
  const [filtersState, setFiltersState] = useState<FilterState>({ branch: "all", curve: "all", productType: "all", family: "all", subfamily: "all" });
  const input = useMemo(() => ({ branch: filtersState.branch === "all" ? undefined : filtersState.branch, curve: filtersState.curve === "all" ? undefined : filtersState.curve as "A" | "B" | "C" | "D" | "E", productType: filtersState.productType === "all" ? undefined : filtersState.productType as "ME" | "PE", family: filtersState.family === "all" ? undefined : filtersState.family, subfamily: filtersState.subfamily === "all" ? undefined : filtersState.subfamily }), [filtersState]);
  const { data: filters } = trpc.analytics.filterOptions.useQuery();
  const { data, isLoading } = trpc.analytics.dashboard.useQuery(input);
  const hasImport = Boolean(data?.currentImport);
  const selectClass = "control";

  return <div className="mx-auto max-w-[1440px]"><section className="relative overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-8 text-white sm:px-9 sm:py-11"><span className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-[#9fc7ea] opacity-90" /><span className="absolute bottom-[-88px] right-[18%] h-48 w-48 rounded-[40%] bg-[#eab6c6] opacity-90" /><div className="relative max-w-3xl"><p className="text-[11px] font-extrabold uppercase tracking-[0.2em] text-[#b8d5ef]">Análise Protheus</p><h1 className="mt-3 text-3xl font-extrabold tracking-[-0.055em] sm:text-5xl">Estoque em perspectiva.</h1><p className="mt-4 max-w-2xl text-sm font-medium leading-6 text-slate-300 sm:text-base">Vendas, estoque financeiro, giro, cobertura e excedente das unidades priorizadas.</p></div></section>
    {!hasImport && !isLoading ? <section className="sc-surface mt-7 flex flex-col items-start gap-5 p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"><div><p className="eyebrow">Primeira carga</p><h2 className="mt-2 text-xl font-extrabold tracking-tight text-slate-950">Importe a planilha extraída do Protheus.</h2><p className="mt-2 max-w-xl text-sm font-medium leading-6 text-slate-500">Os indicadores serão atualizados a partir do arquivo Excel validado.</p></div><Button onClick={() => setLocation("/importar")} className="shrink-0 bg-slate-950 text-white hover:bg-slate-800"><FileUp className="mr-2 h-4 w-4" />Importar planilha</Button></section> : <>
      <section className="sc-surface mt-7 p-5 sm:p-6"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5"><Filter label="Unidade" value={filtersState.branch} onChange={value => setFiltersState({ ...filtersState, branch: value })} options={filters?.branches ?? []} className={selectClass} allLabel="Todas as unidades" /><Filter label="Curva ABCDE" value={filtersState.curve} onChange={value => setFiltersState({ ...filtersState, curve: value })} options={filters?.curves ?? []} className={selectClass} allLabel="Todas as curvas" /><Filter label="Tipo de produto" value={filtersState.productType} onChange={value => setFiltersState({ ...filtersState, productType: value })} options={filters?.productTypes ?? []} className={selectClass} allLabel="Todos os tipos" /><Filter label="Família" value={filtersState.family} onChange={value => setFiltersState({ ...filtersState, family: value })} options={filters?.families ?? []} className={selectClass} allLabel="Todas as famílias" /><Filter label="Subfamília" value={filtersState.subfamily} onChange={value => setFiltersState({ ...filtersState, subfamily: value })} options={filters?.subfamilies ?? []} className={selectClass} allLabel="Todas as subfamílias" /></div><p className="mt-5 text-xs font-semibold text-slate-500">Última carga: <span className="text-slate-700">{data?.currentImport?.fileName}</span> em {formatDate(data?.currentImport?.importedAt)}.</p></section>
      <section className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5">{metrics.map(metric => { const Icon = metric.icon; const value = data?.summary[metric.key] ?? 0; return <article className="sc-surface min-h-40 p-5" key={metric.key}><span className={`absolute -right-5 -top-6 h-20 w-20 rounded-full opacity-70 ${metric.tone === "blue" ? "bg-[#c8e0f3]" : "bg-[#f1ccd7]"}`} /><div className="relative flex h-full flex-col justify-between"><div className="flex items-start justify-between gap-3"><p className="max-w-[11rem] text-sm font-semibold leading-5 text-slate-600">{metric.label}</p><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-950 text-white shadow-sm"><Icon className="h-4 w-4" /></span></div><p className="mt-7 text-3xl font-extrabold tracking-[-0.06em] text-slate-950">{isLoading ? "—" : metric.format(value)}</p></div></article>; })}</section>
      <section className="mt-5 grid gap-5 xl:grid-cols-2"><AnalyticsTable title="Giro por unidade" groupLabel="Unidade" icon={Store} rows={data?.byBranch ?? []} /><AnalyticsTable title="Giro por curva" groupLabel="Curva" icon={ChartNoAxesCombined} rows={data?.byCurve ?? []} /><AnalyticsTable title="Giro por família" groupLabel="Família" icon={Tags} rows={data?.byFamily ?? []} /><AnalyticsTable title="Giro por subfamília" groupLabel="Subfamília" icon={Tags} rows={data?.bySubfamily ?? []} /></section>
    </>}</div>;
}

function Filter({ label, value, onChange, options, allLabel, className }: { label: string; value: string; onChange: (value: string) => void; options: string[]; allLabel: string; className: string }) { return <label className="grid gap-2"><span className="text-xs font-extrabold uppercase tracking-[0.1em] text-slate-500">{label}</span><select className={className} value={value} onChange={event => onChange(event.target.value)}><option value="all">{allLabel}</option>{options.map(option => <option value={option} key={option}>{option || "Não informado"}</option>)}</select></label>; }

function AnalyticsTable({ title, groupLabel, icon: Icon, rows }: { title: string; groupLabel: string; icon: typeof Store; rows: Array<{ label: string; salesValue13M: number; stockValue: number; turnover: number; coverageDays: number; excessValue: number }> }) { return <section className="sc-surface overflow-hidden"><div className="flex items-center gap-3 border-b border-slate-100 px-5 py-5 sm:px-7"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#dcebf7] text-slate-950"><Icon className="h-4 w-4" /></span><h2 className="text-base font-extrabold tracking-tight text-slate-950">{title}</h2></div><Table><TableHeader><TableRow><TableHead>{groupLabel}</TableHead><TableHead>Giro</TableHead><TableHead>Vendas</TableHead><TableHead>Estoque</TableHead><TableHead>Cobertura</TableHead><TableHead>Excedente</TableHead></TableRow></TableHeader><TableBody>{rows.length === 0 && <TableRow><TableCell colSpan={6} className="h-28 text-center text-sm font-medium text-slate-500">Nenhum dado encontrado para os filtros selecionados.</TableCell></TableRow>}{rows.map(row => <TableRow key={row.label}><TableCell className="max-w-48 font-bold text-slate-950">{row.label}</TableCell><TableCell>{formatNumber(row.turnover, 2)}</TableCell><TableCell>{formatMoney(row.salesValue13M)}</TableCell><TableCell>{formatMoney(row.stockValue)}</TableCell><TableCell>{formatNumber(row.coverageDays, 1)} dias</TableCell><TableCell>{formatMoney(row.excessValue)}</TableCell></TableRow>)}</TableBody></Table></section>; }
