import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatDate, formatMoney, formatNumber } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Boxes, ChartNoAxesCombined, CircleDollarSign, FileUp, Lightbulb, RotateCw, Store, Tags } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

const metrics = [
  { key: "salesValue13M", label: "Vendas acumuladas", icon: CircleDollarSign, tone: "blue", format: formatMoney },
  { key: "stockValue", label: "Estoque financeiro", icon: Boxes, tone: "pink", format: formatMoney },
  { key: "turnover", label: "Giro", icon: RotateCw, tone: "blue", format: (value: number) => formatNumber(value, 2) },
  { key: "excessValue", label: "Excedente", icon: ChartNoAxesCombined, tone: "blue", format: formatMoney },
] as const;

type FilterState = { importId: string; branch: string; curve: string; productType: string; mrp: string; family: string; subfamily: string };

export default function Dashboard() {
  const [, setLocation] = useLocation();
  const [filtersState, setFiltersState] = useState<FilterState>({ importId: "latest", branch: "all", curve: "all", productType: "all", mrp: "all", family: "all", subfamily: "all" });
  const [showFamily, setShowFamily] = useState(true);
  const [showSubfamily, setShowSubfamily] = useState(true);
  const { data: imports = [] } = trpc.analytics.imports.useQuery();
  const selectedImportId = filtersState.importId === "latest" ? undefined : Number(filtersState.importId);
  const input = useMemo(() => ({ importId: selectedImportId, branch: filtersState.branch === "all" ? undefined : filtersState.branch, curve: filtersState.curve === "all" ? undefined : filtersState.curve as "A" | "B" | "C" | "D" | "E", productType: filtersState.productType === "all" ? undefined : filtersState.productType as "ME" | "PE", mrp: filtersState.mrp === "all" ? undefined : filtersState.mrp as "Sim" | "Não", family: filtersState.family === "all" ? undefined : filtersState.family, subfamily: filtersState.subfamily === "all" ? undefined : filtersState.subfamily }), [filtersState, selectedImportId]);
  const { data: filters } = trpc.analytics.filterOptions.useQuery({ importId: selectedImportId });
  const evolutionInput = useMemo(() => { const { importId: _importId, ...rest } = input; return rest; }, [input]);
  const { data, isLoading } = trpc.analytics.dashboard.useQuery(input);
  const { data: evolution = [] } = trpc.analytics.evolution.useQuery(evolutionInput);
  const hasImport = Boolean(data?.currentImport);
  const selectClass = "control";

  return <div className="mx-auto max-w-[1440px]"><section className="relative overflow-hidden rounded-[2rem] bg-slate-950 px-6 py-8 text-white sm:px-9 sm:py-11"><span className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-[#9fc7ea] opacity-90" /><span className="absolute bottom-[-88px] right-[18%] h-48 w-48 rounded-[40%] bg-[#eab6c6] opacity-90" /><div className="relative max-w-3xl"><p className="text-[11px] font-extrabold uppercase tracking-[0.2em] text-[#b8d5ef]">Análise Protheus</p><h1 className="mt-3 text-3xl font-extrabold tracking-[-0.055em] sm:text-5xl">Estoque em perspectiva.</h1><p className="mt-4 max-w-2xl text-sm font-medium leading-6 text-slate-300 sm:text-base">Vendas, estoque financeiro, giro e excedente das unidades priorizadas.</p></div></section>
    {!hasImport && !isLoading ? <section className="sc-surface mt-7 flex flex-col items-start gap-5 p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"><div><p className="eyebrow">Primeira carga</p><h2 className="mt-2 text-xl font-extrabold tracking-tight text-slate-950">Importe a planilha extraída do Protheus.</h2><p className="mt-2 max-w-xl text-sm font-medium leading-6 text-slate-500">Os indicadores serão atualizados a partir do arquivo Excel validado.</p></div><Button onClick={() => setLocation("/importar")} className="shrink-0 bg-slate-950 text-white hover:bg-slate-800"><FileUp className="mr-2 h-4 w-4" />Importar planilha</Button></section> : <>
      <section className="sc-surface mt-7 p-5 sm:p-6"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6"><Filter label="Versão da carga" value={filtersState.importId} onChange={value => setFiltersState({ ...filtersState, importId: value, family: "all", subfamily: "all" })} options={imports.map(item => String(item.id))} optionLabels={Object.fromEntries(imports.map(item => [String(item.id), `${item.fileName} · ${formatDate(item.importedAt)}`]))} className={selectClass} allLabel="Mais recente" /><Filter label="Unidade" value={filtersState.branch} onChange={value => setFiltersState({ ...filtersState, branch: value })} options={filters?.branches ?? []} className={selectClass} allLabel="Todas as unidades" /><Filter label="Curva ABCDE" value={filtersState.curve} onChange={value => setFiltersState({ ...filtersState, curve: value })} options={filters?.curves ?? []} className={selectClass} allLabel="Todas as curvas" /><Filter label="Tipo de produto" value={filtersState.productType} onChange={value => setFiltersState({ ...filtersState, productType: value })} options={filters?.productTypes ?? []} className={selectClass} allLabel="Todos os tipos" /><Filter label="MRP" value={filtersState.mrp} onChange={value => setFiltersState({ ...filtersState, mrp: value })} options={filters?.mrps ?? ["Sim", "Não"]} className={selectClass} allLabel="Todos" /><Filter label="Família" value={filtersState.family} onChange={value => setFiltersState({ ...filtersState, family: value })} options={filters?.families ?? []} className={selectClass} allLabel="Todas as famílias" /><Filter label="Subfamília" value={filtersState.subfamily} onChange={value => setFiltersState({ ...filtersState, subfamily: value })} options={filters?.subfamilies ?? []} className={selectClass} allLabel="Todas as subfamílias" /></div><div className="mt-5 flex flex-wrap items-center gap-4 text-xs font-semibold text-slate-600"><label className="inline-flex items-center gap-2"><input type="checkbox" checked={showFamily} onChange={event => setShowFamily(event.target.checked)} />Mostrar família</label><label className="inline-flex items-center gap-2"><input type="checkbox" checked={showSubfamily} onChange={event => setShowSubfamily(event.target.checked)} />Mostrar subfamília</label><span>Versão analisada: <span className="text-slate-800">{data?.currentImport?.fileName ?? "—"}</span> em {data?.currentImport ? formatDate(data.currentImport.importedAt) : "—"}.</span></div></section>
      <section className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5">{metrics.map(metric => { const Icon = metric.icon; const value = data?.summary[metric.key] ?? 0; return <article className="sc-surface min-h-40 p-5" key={metric.key}><span className={`absolute -right-5 -top-6 h-20 w-20 rounded-full opacity-70 ${metric.tone === "blue" ? "bg-[#c8e0f3]" : "bg-[#f1ccd7]"}`} /><div className="relative flex h-full flex-col justify-between"><div className="flex items-start justify-between gap-3"><p className="max-w-[11rem] text-sm font-semibold leading-5 text-slate-600">{metric.label}</p><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-950 text-white shadow-sm"><Icon className="h-4 w-4" /></span></div><p className="mt-7 text-3xl font-extrabold tracking-[-0.06em] text-slate-950">{isLoading ? "—" : metric.format(value)}</p></div></article>; })}</section>
      <section className="sc-surface mt-5 p-5 sm:p-6"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Leitura operacional</p><h2 className="mt-2 text-xl font-extrabold tracking-tight text-slate-950">Qualidade do estoque</h2></div><p className="max-w-xl text-xs font-semibold leading-5 text-slate-500">Sinais calculados sobre o estoque financeiro selecionado: parado sem vendas, cobertura inferior a 30 dias e excedente informado na fonte.</p></div><div className="mt-5 grid gap-3 md:grid-cols-3"><QualityCard label="Estoque sem vendas" value={data?.quality.stockWithoutSalesValue ?? 0} hint="Custo de itens com vendas 13M iguais a zero e saldo positivo." /><QualityCard label="Cobertura baixa" value={data?.quality.lowCoverageStockValue ?? 0} hint="Estoque financeiro com cobertura inferior a 30 dias." /><QualityCard label="Excedente identificado" value={data?.quality.excessStockValue ?? 0} hint="Valor de excedente informado pela extração do Protheus." /></div><div className="mt-5 grid gap-3 lg:grid-cols-3"><Recommendation icon={AlertTriangle} title="Saneamento de parados" active={(data?.quality.stockWithoutSalesValue ?? 0) > 0} text="Priorize a validação de itens sem vendas: revise cadastro, demanda, transferência entre unidades e eventual descontinuação antes de novas compras." /><Recommendation icon={Lightbulb} title="Parâmetros de reposição" active={(data?.quality.lowCoverageStockValue ?? 0) > 0} text="Itens com cobertura inferior a 30 dias pedem revisão do MRP, do estoque de segurança e do prazo de abastecimento por unidade." /><Recommendation icon={ChartNoAxesCombined} title="Ação sobre excedentes" active={(data?.quality.excessStockValue ?? 0) > 0} text="Confronte excedente, curva ABCDE e giro para bloquear compras desnecessárias e avaliar redistribuição para unidades com maior consumo." /></div></section>
      <section className="sc-surface mt-5 overflow-hidden"><div className="flex flex-col gap-2 border-b border-slate-100 px-5 py-5 sm:flex-row sm:items-end sm:justify-between sm:px-7"><div><p className="eyebrow">Série histórica</p><h2 className="mt-2 text-base font-extrabold tracking-tight text-slate-950">Evolução do giro por carga</h2></div><p className="text-xs font-semibold text-slate-500">A comparação considera as versões importadas e os filtros atuais.</p></div><Table><TableHeader><TableRow><TableHead>Versão</TableHead><TableHead>Data</TableHead><TableHead>Giro</TableHead><TableHead>Vendas</TableHead><TableHead>Estoque</TableHead></TableRow></TableHeader><TableBody>{evolution.length === 0 && <TableRow><TableCell colSpan={5} className="h-24 text-center text-sm font-medium text-slate-500">Nenhuma versão histórica encontrada para os filtros selecionados.</TableCell></TableRow>}{evolution.map(point => <TableRow key={point.importId}><TableCell className="font-bold text-slate-950">{point.fileName}</TableCell><TableCell>{formatDate(point.importedAt)}</TableCell><TableCell>{formatNumber(point.turnover, 2)}</TableCell><TableCell>{formatMoney(point.salesValue13M)}</TableCell><TableCell>{formatMoney(point.stockValue)}</TableCell></TableRow>)}</TableBody></Table></section>
      <section className="mt-5 grid gap-5 xl:grid-cols-2"><AnalyticsTable title="Giro por unidade" groupLabel="Unidade" icon={Store} rows={data?.byBranch ?? []} /><AnalyticsTable title="Giro por curva" groupLabel="Curva" icon={ChartNoAxesCombined} rows={data?.byCurve ?? []} />{showFamily && <AnalyticsTable title="Giro por família" groupLabel="Família" icon={Tags} rows={data?.byFamily ?? []} />} {showSubfamily && <AnalyticsTable title="Giro por subfamília" groupLabel="Subfamília" icon={Tags} rows={data?.bySubfamily ?? []} />}</section>
    </>}</div>;
}

function Filter({ label, value, onChange, options, optionLabels, allLabel, className }: { label: string; value: string; onChange: (value: string) => void; options: string[]; optionLabels?: Record<string, string>; allLabel: string; className: string }) { return <label className="grid gap-2"><span className="text-xs font-extrabold uppercase tracking-[0.1em] text-slate-500">{label}</span><select className={className} value={value} onChange={event => onChange(event.target.value)}><option value="all">{allLabel}</option>{options.map(option => <option value={option} key={option}>{optionLabels?.[option] ?? (option || "Não informado")}</option>)}</select></label>; }

function QualityCard({ label, value, hint }: { label: string; value: number; hint: string }) { return <article className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><p className="text-sm font-extrabold text-slate-800">{label}</p><p className="mt-3 text-2xl font-extrabold tracking-tight text-slate-950">{formatMoney(value)}</p><p className="mt-2 text-xs font-medium leading-5 text-slate-500">{hint}</p></article>; }

function Recommendation({ icon: Icon, title, active, text }: { icon: typeof AlertTriangle; title: string; active: boolean; text: string }) { return <article className={`rounded-2xl border p-4 ${active ? "border-[#f0c3cf] bg-[#fff8fa]" : "border-slate-100 bg-white"}`}><div className="flex items-center gap-2"><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${active ? "bg-[#f1ccd7] text-slate-950" : "bg-slate-100 text-slate-500"}`}><Icon className="h-4 w-4" /></span><p className="text-sm font-extrabold text-slate-800">{title}</p></div><p className="mt-3 text-xs font-medium leading-5 text-slate-600">{text}</p><p className="mt-3 text-[11px] font-extrabold uppercase tracking-[0.12em] text-slate-400">{active ? "Sinal presente na seleção" : "Sem sinal na seleção"}</p></article>; }

function AnalyticsTable({ title, groupLabel, icon: Icon, rows }: { title: string; groupLabel: string; icon: typeof Store; rows: Array<{ label: string; salesValue13M: number; stockValue: number; turnover: number; coverageDays: number; excessValue: number }> }) { return <section className="sc-surface overflow-hidden"><div className="flex items-center gap-3 border-b border-slate-100 px-5 py-5 sm:px-7"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#dcebf7] text-slate-950"><Icon className="h-4 w-4" /></span><h2 className="text-base font-extrabold tracking-tight text-slate-950">{title}</h2></div><Table><TableHeader><TableRow><TableHead>{groupLabel}</TableHead><TableHead>Giro</TableHead><TableHead>Vendas</TableHead><TableHead>Estoque</TableHead><TableHead>Cobertura</TableHead><TableHead>Excedente</TableHead></TableRow></TableHeader><TableBody>{rows.length === 0 && <TableRow><TableCell colSpan={6} className="h-28 text-center text-sm font-medium text-slate-500">Nenhum dado encontrado para os filtros selecionados.</TableCell></TableRow>}{rows.map(row => <TableRow key={row.label}><TableCell className="max-w-48 font-bold text-slate-950">{row.label}</TableCell><TableCell>{formatNumber(row.turnover, 2)}</TableCell><TableCell>{formatMoney(row.salesValue13M)}</TableCell><TableCell>{formatMoney(row.stockValue)}</TableCell><TableCell>{formatNumber(row.coverageDays, 1)} dias</TableCell><TableCell>{formatMoney(row.excessValue)}</TableCell></TableRow>)}</TableBody></Table></section>; }
