import { AlertTriangle, CheckCircle2, Loader2, RefreshCw, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

const nf = (value: number) => value.toLocaleString("pt-BR");
export default function OperationalAudit() {
  const query = trpc.operationalAudit.report.useQuery(undefined, { retry: false });
  const report = query.data;
  return <main className="page-wrap max-w-7xl">
    <header className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Administração · Dados operacionais</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-0.055em] text-slate-950">Auditoria de cruzamentos</h1><p className="mt-3 max-w-3xl text-sm font-medium leading-6 text-slate-500">Consulta somente leitura entre cadastros, pedidos, notas fiscais e estoque. Nenhum dado é alterado.</p></div><Button variant="outline" onClick={() => query.refetch()} disabled={query.isFetching}><RefreshCw className={`mr-2 h-4 w-4 ${query.isFetching ? "animate-spin" : ""}`} />Atualizar</Button></header>
    {query.isLoading && <div className="sc-surface flex items-center gap-3 p-6"><Loader2 className="h-5 w-5 animate-spin" />Carregando a auditoria...</div>}
    {query.error && <div className="sc-surface border border-rose-200 bg-rose-50 p-6 text-sm font-semibold text-rose-800">Não foi possível consultar: {query.error.message}</div>}
    {report && <><div className="mb-5 grid gap-4 sm:grid-cols-3"><div className="sc-surface p-5"><p className="text-xs font-bold uppercase text-slate-500">Status</p><p className="mt-2 flex items-center gap-2 text-lg font-extrabold text-emerald-700"><ShieldCheck className="h-5 w-5" />Somente leitura</p></div><div className="sc-surface p-5"><p className="text-xs font-bold uppercase text-slate-500">Exceções</p><p className="mt-2 text-2xl font-extrabold">{nf(report.exceptionCount)}</p></div><div className="sc-surface p-5"><p className="text-xs font-bold uppercase text-slate-500">Duplicidades</p><p className="mt-2 text-2xl font-extrabold">{nf(report.duplicateCount)}</p></div></div>
      <section className="sc-surface overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-extrabold">Indicadores por cruzamento</h2><p className="mt-1 text-xs text-slate-500">Gerado em {new Date(report.generatedAt).toLocaleString("pt-BR")}</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs font-extrabold uppercase text-slate-500"><tr>{["Fonte","Total","Direto","Agregado","Não encontrado","Correspondência"].map((x,i)=><th className={`p-3 ${i ? "text-right" : ""}`} key={x}>{x}</th>)}</tr></thead><tbody>{report.metrics.map(metric => <tr key={metric.source} className="border-t border-slate-100"><td className="p-3 font-bold">{metric.source}</td><td className="p-3 text-right">{nf(metric.total)}</td><td className="p-3 text-right">{nf(metric.direct)}</td><td className="p-3 text-right">{nf(metric.aggregate)}</td><td className="p-3 text-right">{nf(metric.notFound)}</td><td className="p-3 text-right font-bold">{(metric.matchRate * 100).toFixed(2).replace(".", ",")}%</td></tr>)}</tbody></table></div></section>
      <section className="sc-surface mt-5 overflow-hidden"><div className="flex items-center gap-2 border-b border-slate-100 px-5 py-4"><AlertTriangle className="h-5 w-5 text-amber-600" /><div><h2 className="font-extrabold">Exceções</h2><p className="mt-1 text-xs text-slate-500">Até 500 ocorrências são exibidas.</p></div></div><div className="max-h-[520px] overflow-auto">{report.exceptions.length === 0 ? <p className="p-5 font-semibold text-emerald-700"><CheckCircle2 className="mr-2 inline h-4 w-4" />Nenhuma exceção encontrada.</p> : <table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs font-extrabold uppercase text-slate-500"><tr><th className="p-3">Fonte</th><th className="p-3">Tipo</th><th className="p-3">Chave</th><th className="p-3">Detalhe</th></tr></thead><tbody>{report.exceptions.map((item, index) => <tr key={`${item.sourceKey}-${index}`} className="border-t border-slate-100 align-top"><td className="p-3 font-bold">{item.source}</td><td className="p-3 whitespace-nowrap">{item.kind}</td><td className="p-3 font-mono text-xs">{item.sourceKey}</td><td className="p-3">{item.detail}</td></tr>)}</tbody></table>}</div></section>
      {report.truncated && <p className="mt-4 text-xs font-semibold text-amber-700">Há mais ocorrências do que as exibidas. A consulta completa permanece no backend.</p>}
    </>}
  </main>;
}
