import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { AlertCircle, KeyRound, LoaderCircle, MailCheck, Send, ShieldCheck, UserPlus, UsersRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

type ProfileKey = "development-admin" | "operations-admin" | "manager" | "operator" | "viewer";

export default function UserManagement() {
  const utils = trpc.useUtils();
  const usersQuery = trpc.portal.users.useQuery();
  const profilesQuery = trpc.portal.profiles.useQuery();
  const requestsQuery = trpc.portal.accessRequests.useQuery();
  const users = usersQuery.data ?? [];
  const profiles = profilesQuery.data ?? [];
  const requests = requestsQuery.data ?? [];
  const [newUser, setNewUser] = useState<{ displayName: string; email: string; profileKey: ProfileKey }>({ displayName: "", email: "", profileKey: "operator" });
  const [reviewData, setReviewData] = useState<Record<string, { displayName: string; profileKey: ProfileKey }>>({});
  const refresh = async () => { await Promise.all([utils.portal.users.invalidate(), utils.portal.accessRequests.invalidate(), utils.portal.profiles.invalidate()]); };
  const createUser = trpc.portal.createUser.useMutation({ onSuccess: async () => { await refresh(); setNewUser({ displayName: "", email: "", profileKey: "operator" }); toast.success("Convite enviado e usuário criado."); }, onError: error => toast.error(error.message) });
  const updateUser = trpc.portal.updateUser.useMutation({ onSuccess: async () => { await refresh(); toast.success("Dados do usuário atualizados."); }, onError: error => toast.error(error.message) });
  const resendInvite = trpc.portal.resendInvite.useMutation({ onSuccess: () => toast.success("E-mail de redefinição de senha enviado."), onError: error => toast.error(error.message) });
  const resendActivation = trpc.portal.resendActivationInvite.useMutation({ onSuccess: () => toast.success("Novo convite de ativação enviado."), onError: error => toast.error(error.message) });
  const reviewRequest = trpc.portal.reviewAccessRequest.useMutation({ onSuccess: async () => { await refresh(); toast.success("Solicitação revisada."); }, onError: error => toast.error(error.message) });
  const isLoading = usersQuery.isLoading || profilesQuery.isLoading || requestsQuery.isLoading;
  const queryError = usersQuery.error ?? profilesQuery.error ?? requestsQuery.error;
  const submitUser = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); createUser.mutate(newUser); };

  return <div className="page-wrap"><header className="mb-7"><p className="eyebrow">Administração</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-0.055em] text-slate-950 sm:text-4xl">Usuários e solicitações</h1><p className="mt-3 max-w-2xl text-sm font-medium leading-6 text-slate-500">Crie acessos, acompanhe o status, atribua perfis e revise solicitações do ambiente de homologação.</p></header>
    {queryError ? <Feedback tone="error" text={queryError.message || "Não foi possível carregar as informações administrativas."} action={() => refresh()} /> : isLoading ? <Feedback tone="loading" text="Carregando usuários, perfis e solicitações…" /> : null}
    <section className="sc-surface p-5 sm:p-7"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#dcebf7] text-slate-950"><UserPlus className="h-4 w-4" /></span><div><h2 className="text-base font-extrabold tracking-tight text-slate-950">Novo usuário</h2><p className="text-xs font-medium text-slate-500">O convite permite que a pessoa defina sua própria senha.</p></div></div><form className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-[1fr_1fr_220px_auto] xl:items-end" onSubmit={submitUser}><Field label="Nome"><Input disabled={isLoading || Boolean(queryError)} value={newUser.displayName} onChange={event => setNewUser({ ...newUser, displayName: event.target.value })} required /></Field><Field label="E-mail"><Input disabled={isLoading || Boolean(queryError)} type="email" value={newUser.email} onChange={event => setNewUser({ ...newUser, email: event.target.value })} required /></Field><Field label="Perfil"><ProfileSelect disabled={isLoading || Boolean(queryError)} value={newUser.profileKey} profiles={profiles} onChange={profileKey => setNewUser({ ...newUser, profileKey })} /></Field><Button type="submit" disabled={isLoading || Boolean(queryError) || createUser.isPending} className="bg-slate-950 text-white hover:bg-slate-800">{createUser.isPending ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}Enviar convite</Button></form></section>
    <section className="sc-surface mt-5 overflow-hidden"><div className="flex items-center gap-3 border-b border-slate-100 px-5 py-5 sm:px-7"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f1ccd7] text-slate-950"><UsersRound className="h-4 w-4" /></span><h2 className="text-base font-extrabold tracking-tight text-slate-950">Usuários cadastrados</h2></div><Table><TableHeader><TableRow><TableHead>Usuário</TableHead><TableHead>Perfil</TableHead><TableHead>Status</TableHead><TableHead>Gestão</TableHead></TableRow></TableHeader><TableBody>{!isLoading && users.map(user => { const profile = (user.profiles[0] ?? "operator") as ProfileKey; const status = user.status === "inactive" ? "inactive" : "active"; return <TableRow key={user.id}><TableCell><p className="font-bold text-slate-950">{user.displayName ?? "Sem nome"}</p><p className="mt-1 text-xs font-medium text-slate-500">{user.email}</p></TableCell><TableCell><ProfileSelect disabled={Boolean(queryError)} value={profile} profiles={profiles} onChange={profileKey => updateUser.mutate({ userId: user.id, status, profileKey })} /></TableCell><TableCell><div className="grid gap-1"><select className="control h-8 w-28 text-xs" disabled={Boolean(queryError)} value={status} onChange={event => updateUser.mutate({ userId: user.id, status: event.target.value as "active" | "inactive", profileKey: profile })}><option value="active">Ativo</option><option value="inactive">Inativo</option></select><span className={`text-[10px] font-extrabold uppercase tracking-[0.08em] ${user.activation === "confirmed" ? "text-emerald-700" : "text-amber-700"}`}>{user.activation === "confirmed" ? "Ativação concluída" : "Pendente de ativação"}</span></div></TableCell><TableCell><div className="flex flex-wrap gap-2">{user.isDevelopmentAdmin && <Badge className="bg-[#dcebf7] text-slate-800"><ShieldCheck className="mr-1 h-3 w-3" />Técnico</Badge>}{user.activation === "pending" && <Button size="sm" variant="ghost" disabled={resendActivation.isPending} className="h-8 px-2 text-xs font-bold" onClick={() => resendActivation.mutate({ userId: user.id })}><MailCheck className="mr-1.5 h-3.5 w-3.5" />Ativação</Button>}<Button size="sm" variant="ghost" disabled={resendInvite.isPending} className="h-8 px-2 text-xs font-bold" onClick={() => resendInvite.mutate({ email: user.email })}><KeyRound className="mr-1.5 h-3.5 w-3.5" />Senha</Button></div></TableCell></TableRow>; })}{isLoading && <EmptyRow columns={4} text="Carregando usuários…" />}{!isLoading && !queryError && users.length === 0 && <EmptyRow columns={4} text="Nenhum usuário cadastrado." />}</TableBody></Table></section>
    <section className="sc-surface mt-5 overflow-hidden"><div className="border-b border-slate-100 px-5 py-5 sm:px-7"><h2 className="text-base font-extrabold tracking-tight text-slate-950">Solicitações de acesso</h2></div><Table><TableHeader><TableRow><TableHead>Solicitante</TableHead><TableHead>Justificativa</TableHead><TableHead>Status</TableHead><TableHead>Revisão</TableHead></TableRow></TableHeader><TableBody>{!isLoading && requests.map(request => { const review = reviewData[request.id] ?? { displayName: "", profileKey: "operator" }; return <TableRow key={request.id}><TableCell><p className="font-bold text-slate-950">{request.email}</p><p className="mt-1 text-xs font-medium text-slate-500">{formatDate(request.createdAt)}</p></TableCell><TableCell>{request.reason ?? "—"}</TableCell><TableCell><Badge className={request.status === "pending" ? "bg-[#f3dfc4] text-slate-700" : request.status === "approved" ? "bg-[#dcead9] text-slate-700" : "bg-slate-100 text-slate-600"}>{request.status}</Badge></TableCell><TableCell>{request.status === "pending" ? <div className="grid min-w-64 gap-2"><Input aria-label={`Nome para ${request.email}`} placeholder="Nome do usuário" value={review.displayName} onChange={event => setReviewData({ ...reviewData, [request.id]: { ...review, displayName: event.target.value } })} /><ProfileSelect value={review.profileKey} profiles={profiles} onChange={profileKey => setReviewData({ ...reviewData, [request.id]: { ...review, profileKey } })} /><div className="flex gap-2"><Button size="sm" disabled={reviewRequest.isPending} onClick={() => reviewRequest.mutate({ requestId: request.id, decision: "approved", displayName: review.displayName, profileKey: review.profileKey })}>Aprovar</Button><Button size="sm" variant="ghost" disabled={reviewRequest.isPending} onClick={() => reviewRequest.mutate({ requestId: request.id, decision: "rejected" })}>Recusar</Button></div></div> : "—"}</TableCell></TableRow>; })}{isLoading && <EmptyRow columns={4} text="Carregando solicitações…" />}{!isLoading && !queryError && requests.length === 0 && <EmptyRow columns={4} text="Nenhuma solicitação de acesso." />}</TableBody></Table></section>
  </div>;
}

function Feedback({ tone, text, action }: { tone: "loading" | "error"; text: string; action?: () => void }) { return <div className={`mb-5 flex items-center justify-between gap-4 rounded-2xl border px-4 py-3 text-sm font-semibold ${tone === "error" ? "border-rose-200 bg-rose-50 text-rose-800" : "border-sky-100 bg-sky-50 text-slate-700"}`}><span className="flex items-center gap-2">{tone === "error" ? <AlertCircle className="h-4 w-4" /> : <LoaderCircle className="h-4 w-4 animate-spin" />}{text}</span>{action && <Button size="sm" variant="outline" onClick={action}>Tentar novamente</Button>}</div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2"><Label className="text-xs font-extrabold uppercase tracking-[0.1em] text-slate-500">{label}</Label>{children}</label>; }
function ProfileSelect({ value, profiles, onChange, disabled = false }: { value: ProfileKey; profiles: Array<{ key: string; name: string }>; onChange: (value: ProfileKey) => void; disabled?: boolean }) { return <select className="control" disabled={disabled} value={value} onChange={event => onChange(event.target.value as ProfileKey)}>{profiles.map(profile => <option value={profile.key} key={profile.key}>{profile.name}</option>)}</select>; }
function EmptyRow({ columns, text }: { columns: number; text: string }) { return <TableRow><TableCell colSpan={columns} className="h-28 text-center text-sm font-medium text-slate-500">{text}</TableCell></TableRow>; }
