import * as XLSX from "xlsx";
import { randomUUID } from "node:crypto";
import { createPool, type Pool } from "mysql2/promise";
import { TRPCError } from "@trpc/server";
import { assertApplicationPermission, type PortalIdentity } from "./supabasePortal";
import type { AssetType } from "./assetMaintenance";
let pool: Pool | undefined;
function getPool() { if (!pool) pool = createPool(process.env.DATABASE_URL ?? ""); return pool; }
const nodeForType = (type: AssetType) => type === "forklift" ? "ativos-empilhadeiras" : type === "industrial_equipment" ? "ativos-equipamentos-industria" : "ativos-ferramentas";
const text = (value: unknown) => String(value ?? "").trim();
export type AssetImportRow = { code: string; name: string; serialNumber?: string; status?: string; criticality?: string; sector?: string; productionLine?: string; physicalPosition?: string; metadata?: Record<string, unknown> };
export function parseAssetWorkbook(contentBase64: string, type: AssetType): { rows: AssetImportRow[]; errors: string[] } { const workbook = XLSX.read(Buffer.from(contentBase64, "base64"), { type: "buffer", cellDates: false }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; if (!sheet) throw new TRPCError({ code: "BAD_REQUEST", message: "A planilha não possui uma aba válida." }); const raw = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: "" }); const rows: AssetImportRow[] = []; const errors: string[] = []; raw.forEach((item, index) => { const rowNumber = index + 2; const code = text(item.codigo ?? item.code ?? item["Código"]); const name = text(item.nome ?? item.name ?? item["Nome"]); if (!code || !name) { errors.push(`Linha ${rowNumber}: código e nome são obrigatórios.`); return; } rows.push({ code, name, serialNumber: text(item.numero_serie ?? item.serialNumber) || undefined, status: text(item.status) || undefined, criticality: type === "industrial_equipment" ? text(item.criticidade ?? item.criticality) || undefined : undefined, sector: text(item.setor ?? item.sector) || undefined, productionLine: text(item.linha_producao ?? item.productionLine) || undefined, physicalPosition: text(item.posicao_fisica ?? item.physicalPosition) || undefined, metadata: { importedFromRow: rowNumber, assetType: type } }); }); return { rows, errors }; }
export async function commitAssetImport(type: AssetType, rows: AssetImportRow[], identity: PortalIdentity) { await assertApplicationPermission(identity, nodeForType(type), "manage"); if (!rows.length || rows.length > 10000) throw new TRPCError({ code: "BAD_REQUEST", message: "A prévia deve conter entre 1 e 10.000 linhas válidas." }); const connection = await getPool().getConnection(); try { await connection.beginTransaction(); let inserted = 0; for (const row of rows) { const id = randomUUID(); await connection.query(`INSERT INTO assetAssets (id, assetType, code, name, serialNumber, status, criticality, sector, productionLine, physicalPosition, metadata, createdByUserId) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, [id, type, row.code, row.name, row.serialNumber ?? null, row.status ?? "active", row.criticality ?? null, row.sector ?? null, row.productionLine ?? null, row.physicalPosition ?? null, JSON.stringify(row.metadata ?? {}), identity.id]); await connection.query(`INSERT INTO assetEvents (id, assetId, eventType, details, actorUserId) VALUES (?, ?, 'imported', ?, ?)`, [randomUUID(), id, JSON.stringify({ assetType: type, code: row.code }), identity.id]); inserted += 1; } await connection.commit(); return { inserted }; } catch (error: any) { await connection.rollback(); if (error?.code === "ER_DUP_ENTRY") throw new TRPCError({ code: "CONFLICT", message: "A planilha contém código já cadastrado." }); throw error; } finally { connection.release(); } }
