import { cleanSourceText, normalizeBranchCode, normalizeProductCode, normalizeSupplierKey } from "./operationalNormalization";

export type RegistrationIssue = { row: number; field: string; message: string };
export type RegistrationResult<T> = { rows: T[]; sourceRows: number; skippedRows: number; duplicateRows: number; issues: RegistrationIssue[] };
type CsvRow = string[];

function normalizeHeader(value: unknown) { return cleanSourceText(value).normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-zA-Z0-9]/g, "").toLowerCase(); }
function parseCsv(content: string) { const first = content.split(/\r?\n/).find(line => line.includes(";") || line.includes(",")) ?? ""; const delimiter = first.split(";").length >= first.split(",").length ? ";" : ","; const rows: CsvRow[] = []; let row: string[] = []; let value = ""; let quoted = false; for (let i=0;i<content.length;i+=1) { const c=content[i]; const n=content[i+1]; if(c==='"'&&quoted&&n==='"'){value+='"';i+=1;continue;} if(c==='"'){quoted=!quoted;continue;} if(c===delimiter&&!quoted){row.push(value);value="";continue;} if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i+=1;row.push(value);if(row.some(v=>cleanSourceText(v)!==""))rows.push(row);row=[];value="";continue;} value+=c;} if(value||row.length){row.push(value);if(row.some(v=>cleanSourceText(v)!==""))rows.push(row);} return rows; }
function headerIndex(rows: CsvRow[], required: string[]) { return rows.findIndex(row => required.every(field => row.some(h => normalizeHeader(h) === normalizeHeader(field)))); }
function mapHeaders(header: CsvRow) { return new Map(header.map((value,index)=>[normalizeHeader(value),index])); }
function get(row: CsvRow, map: Map<string,number>, ...aliases: string[]) { for(const alias of aliases){const index=map.get(normalizeHeader(alias));if(index!==undefined)return cleanSourceText(row[index]);}return ""; }
function emptyResult<T>(): RegistrationResult<T> { return { rows: [], sourceRows: 0, skippedRows: 0, duplicateRows: 0, issues: [] }; }
function invalidScientific(value: string) { return /^[-+]?\d+(?:[,.]\d+)?e[-+]?\d+$/i.test(value) || /^[-+]?\d+[,.]?\d*e[+]?\d+$/i.test(value); }
function decodeContent(content: Buffer|string) { return typeof content === "string" ? content : new TextDecoder("windows-1252").decode(content); }

export type Sb1Row = { productCode: string; normalizedProductCode: string; aggregateProductCode: string; normalizedAggregateProductCode: string; description: string; type: string; family: string; subfamily: string; ncm: string; inclusionDate: string; };
export function parseSb1(content: Buffer|string): RegistrationResult<Sb1Row> { const rows=parseCsv(decodeContent(content)); const header=headerIndex(rows,["Codigo","Cod Agregado","Descricao"]); if(header<0)throw new Error("SB1: cabeçalho não encontrado."); const map=mapHeaders(rows[header]); const out=emptyResult<Sb1Row>(); const seen=new Map<string,number>(); rows.slice(header+1).forEach((row,offset)=>{if(!row.some(v=>cleanSourceText(v)))return;out.sourceRows+=1;const rawCode=get(row,map,"Codigo"),rawAggregate=get(row,map,"Cod Agregado"),code=cleanSourceText(rawCode),aggregate=cleanSourceText(rawAggregate);if(!code||invalidScientific(rawCode)||invalidScientific(rawAggregate)){out.skippedRows+=1;out.issues.push({row:header+offset+2,field:"Codigo",message:"Código vazio ou em notação científica; reextração necessária."});return;}const current={productCode:code,normalizedProductCode:normalizeProductCode(code),aggregateProductCode:aggregate,normalizedAggregateProductCode:normalizeProductCode(aggregate),description:get(row,map,"Descricao"),type:get(row,map,"Tipo"),family:get(row,map,"Familia"),subfamily:get(row,map,"Sub-familia"),ncm:get(row,map,"Pos.IPI/NCM"),inclusionDate:get(row,map,"Dt Inclusao")};const previous=seen.get(code);if(previous!==undefined){out.duplicateRows+=1;out.issues.push({row:header+offset+2,field:"Codigo",message:`Código duplicado; linha anterior ${previous}.`});const index=previous-header-2;const prior=out.rows[index];if(prior&&Object.values(current).filter(Boolean).length>Object.values(prior).filter(Boolean).length)out.rows[index]=current;return;}seen.set(code,header+offset+2);out.rows.push(current);});return out; }

export type SbzRow = { branchCode: string; productCode: string; taxGroup: string; type: string; minStock: string; maxStock: string; origin: string; mrp: boolean; fiscalClass: string; };
export function parseSbz(content: Buffer|string): RegistrationResult<SbzRow> { const rows=parseCsv(decodeContent(content));const header=headerIndex(rows,["Filial","Codigo","Entra MRP"]);if(header<0)throw new Error("SBZ: cabeçalho não encontrado.");const map=mapHeaders(rows[header]);const out=emptyResult<SbzRow>();const seen=new Set<string>();rows.slice(header+1).forEach((row,offset)=>{if(!row.some(v=>cleanSourceText(v)))return;out.sourceRows+=1;const branch=normalizeBranchCode(get(row,map,"Filial")),raw=get(row,map,"Codigo"),product=normalizeProductCode(raw);if(!branch||!product||invalidScientific(raw)){out.skippedRows+=1;out.issues.push({row:header+offset+2,field:"Codigo",message:"Linha sem código de produto válido."});return;}const key=`${branch}|${product}`;if(seen.has(key)){out.duplicateRows+=1;out.issues.push({row:header+offset+2,field:"Codigo",message:`Chave código+filial duplicada: ${key}.`});return;}seen.add(key);out.rows.push({branchCode:branch,productCode:product,taxGroup:get(row,map,"Grupo Trib."),type:get(row,map,"Tipo"),minStock:get(row,map,"Estoq Minimo"),maxStock:get(row,map,"Estoq Maximo"),origin:get(row,map,"Origem"),mrp:/^(sim|s|yes|1)$/i.test(get(row,map,"Entra MRP")),fiscalClass:get(row,map,"Class.Fiscal")});});return out; }

export type Sb5Row = { productCode: string; technicalFamily: string; partFamily: string; partBrand: string; partLine: string; };
export function parseSb5(content: Buffer|string): RegistrationResult<Sb5Row> { const rows=parseCsv(decodeContent(content));const header=headerIndex(rows,["Produto","Marca Peca"]);if(header<0)throw new Error("SB5: cabeçalho não encontrado.");const map=mapHeaders(rows[header]);const out=emptyResult<Sb5Row>();const seen=new Set<string>();rows.slice(header+1).forEach((row,offset)=>{if(!row.some(v=>cleanSourceText(v)))return;out.sourceRows+=1;const raw=get(row,map,"Produto"),product=normalizeProductCode(raw);if(!product||invalidScientific(raw)){out.skippedRows+=1;out.issues.push({row:header+offset+2,field:"Produto",message:"Produto vazio ou em notação científica."});return;}if(seen.has(product)){out.duplicateRows+=1;out.issues.push({row:header+offset+2,field:"Produto",message:`Produto alternativo duplicado: ${product}.`});return;}seen.add(product);out.rows.push({productCode:product,technicalFamily:get(row,map,"Familia Tec."),partFamily:get(row,map,"Família Peça","Familia Peca"),partBrand:get(row,map,"Marca Peca"),partLine:get(row,map,"Linha Peça","Linha Peca")});});return out; }

export type Sa2Row = { supplierCode: string; store: string; document: string; legalName: string; tradeAddress: string; number: string; zipCode: string; neighborhood: string; municipality: string; state: string; };
export function parseSa2(content: Buffer|string): RegistrationResult<Sa2Row> { const rows=parseCsv(decodeContent(content));const header=headerIndex(rows,["Codigo","Loja","Razao Social"]);if(header<0)throw new Error("SA2: cabeçalho não encontrado.");const map=mapHeaders(rows[header]);const out=emptyResult<Sa2Row>();const seen=new Set<string>();rows.slice(header+1).forEach((row,offset)=>{if(!row.some(v=>cleanSourceText(v)))return;out.sourceRows+=1;const code=get(row,map,"Codigo"),store=get(row,map,"Loja"),name=get(row,map,"Razao Social"),document=get(row,map,"CNPJ/CPF");if(!code||!store||!name||/^\.\s*\.\s*\/\s*-?$/.test(document)){out.skippedRows+=1;out.issues.push({row:header+offset+2,field:"Codigo/Loja",message:"Fornecedor sem chave ou linha de controle da extração."});return;}const key=normalizeSupplierKey(code,store);if(seen.has(key)){out.duplicateRows+=1;out.issues.push({row:header+offset+2,field:"Codigo+Loja",message:`Fornecedor duplicado: ${key}.`});return;}seen.add(key);out.rows.push({supplierCode:code,store,document,legalName:name,tradeAddress:get(row,map,"Endereço","Endereco"),number:get(row,map,"Numero"),zipCode:get(row,map,"CEP"),neighborhood:get(row,map,"Bairro"),municipality:get(row,map,"Município","Municipio","Munícipio"),state:get(row,map,"Estado")});});return out; }
